### ISSUE TITLE
ContinuedFraction v.0.6 Package Status

### ISSUE THREAD

**Issue by prairie-guy** [johnmyleswhite/ContinuedFractions.jl#13]
I am interested in using `ContinuedFractions`, but am unable to do so with v.0.6. It appears that the github repo for `src/ContinuedFractions.jl` is much more current than the file downloaded with Pkg.add. 

I have downloaded the most current version and it seems to work fine for me. It would, however, be good to be assured that it has been tested more fully. Moreover, it would also be nice to be able to use the package management system on other machines seamlessly.

Are there plans to maintain this package?

Many thanks. Appreciate the work that has gone into `ContinuedFractions`.

**Comment by rdeits** [comment]
@johnmyleswhite @anthonyclays I can do the work of creating a METADATA PR to update the published version of this package, if it's OK with you.

**Comment by anthonyclays** [comment]
Sure, that would be welcome - I haven't been involved for quite some time.

**Comment by rdeits** [comment]
Great! I just need #14 merged first.

**Comment by johnmyleswhite** [comment]
@rdeits, I've added you as a collaborator to simplify these things going forward.

**Comment by rdeits** [comment]
Ok, thanks!

**Comment by rdeits** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10946

**Comment by rdeits** [comment]
@prairie-guy ContinuedFractions v0.1.0 was just published and supports julia v0.4 through v0.7, so I think this issue is resolved. Please let me know if it's not.
