### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [johnmyleswhite/ContinuedFractions.jl#18]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by johnmyleswhite** [comment]
@rdeits or @anthonyclays: Do you either want this package to survive or should we let it die out?

**Comment by rdeits** [comment]
AFAIK this package *works* fine on 1.0, it just never had a release since the 1.0 compatibility updates. That seems like an easy thing to do (especially with https://github.com/JuliaRegistries/Registrator.jl/#registrator ) that will ensure this package works for the whole lifetime of Julia 1.0. I don't have permissions to add Registrator to this repo, but @johnmyleswhite you should be able to do so.

**Comment by chakravala** [comment]
if nobody else wants to maintain this package, I would gladly be willing to adopt it, it turns out that my username chakravala is inspired by a continued fraction type algorithm, so I'd be also willing to maintain this package if nobody else

**Comment by davidavdav** [comment]
Please do so, I'd be interested in using the package and without a form of registration that is cumbersome.
